server:
  port: 9001
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678
    url: jdbc:mysql://192.168.1.101:3306/lary
  profiles:
    active: dev
  data:
    redis:
      database: 0
      host: 127.0.0.1
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    sql: debug
    web: debug
# retrofit spring boot starter config list
retrofit:
  # 全局转换器工厂
  global-converter-factories:
    - com.github.lianjiatech.retrofit.spring.boot.core.BasicTypeConverterFactory
    - retrofit2.converter.jackson.JacksonConverterFactory
  # 全局调用适配器工厂(组件扩展的调用适配器工厂已经内置，这里请勿重复配置)
  global-call-adapter-factories:

  # 全局日志打印配置
  global-log:
    # 启用日志打印
    enable: true
    # 全局日志打印级别
    log-level: debug
    # 全局日志打印策略
    log-strategy: basic
    # 是否聚合打印请求日志
    aggregate: true

  # 全局重试配置
  global-retry:
    # 是否启用全局重试
    enable: false
    # 全局重试间隔时间
    interval-ms: 100
    # 全局最大重试次数
    max-retries: 2
    # 全局重试规则
    retry-rules:
      - response_status_not_2xx
      - occur_io_exception

  # 全局超时时间配置
  global-timeout:
    # 全局读取超时时间
    read-timeout-ms: 10000
    # 全局写入超时时间
    write-timeout-ms: 10000
    # 全局连接超时时间
    connect-timeout-ms: 10000
    # 全局完整调用超时时间
    call-timeout-ms: 0

  # 熔断降级配置
  degrade:
    # 熔断降级类型。默认none，表示不启用熔断降级
    degrade-type: none
    # 全局sentinel降级配置
    global-sentinel-degrade:
      # 是否开启
      enable: false
      # 各降级策略对应的阈值。平均响应时间(ms)，异常比例(0-1)，异常数量(1-N)
      count: 1000
      # 熔断时长，单位为 s
      time-window: 5
      # 降级策略（0：平均响应时间；1：异常比例；2：异常数量）
      grade: 0

    # 全局resilience4j降级配置
    global-resilience4j-degrade:
      # 是否开启
      enable: false
      # 根据该名称从#{@link CircuitBreakerConfigRegistry}获取CircuitBreakerConfig，作为全局熔断配置
      circuit-breaker-config-name: defaultCircuitBreakerConfig
  # 自动设置PathMathInterceptor的scope为prototype
  auto-set-prototype-scope-for-path-math-interceptor: true
wk:
  base:
    url: http://127.0.0.1:5001

aliyun:
  sms:
    access-key-id: test
    sign-name: test
    template-code: test
    access-key-secret: test
lary:
  register:
    only-china: true
    username-on: true
    sticker-add-off: true
    offe: false # 这里使用 offe 是因为 off会注入不成功
  shortno:
    num-on: true
    num-len: 5
    edit-off: true
  account:
    admin-uid: lary_admin_uid
    file-helper-uid: lary_file_helper_uid
    system-group-name: lary_system_group_name
    system-group-uid: lary_system_group_uid
    system-uid: lary_system_uid
  redis:
    friend-apply-expire: 200
    friend-apply-token-cache-prefix: "apply:"
    login-device-cache-expire: 200
    login-device-cache-prefix: "device:"
    token-cache-prefix: "lary:"
    token-expire: 200
    uid-token-cache-prefix: "uid:"
  group:
    same-day-create-max-count: 5
    allow-view-history-msg-status: true