rocketmq:
  consumer:
    group: springboot_consumer_group
    # 一次拉取消息最大值，注意是拉取消息的最大值而非消费最大值
    pull-batch-size: 10
  name-server: 127.0.0.1:9876
  producer:
    # 发送同一类消息的设置为同一个group，保证唯一
    group: springboot_producer_group
    # 发送消息超时时间，默认3000
    sendMessageTimeout: 10000
    # 发送消息失败重试次数，默认2
    retryTimesWhenSendFailed: 2
    # 异步消息重试此处，默认2
    retryTimesWhenSendAsyncFailed: 2
    # 消息最大长度，默认1024 * 1024 * 4(默认4M)
    maxMessageSize: 4096
    # 压缩消息阈值，默认4k(1024 * 4)
    compressMessageBodyThreshold: 4096
    # 是否在内部发送失败时重试另一个broker，默认false
    retryNextServer: false
lary:
  register:
    only-china: true
    username-on: true
    sticker-add-off: true
    offe: false # 这里使用 offe 是因为 off会注入不成功
  shortno:
    num-on: true
    num-len: 5
    edit-off: true
  account:
    admin-uid: lary_admin_uid
    file-helper-uid: lary_file_helper_uid
    system-group-name: lary_system_group_name
    system-group-uid: lary_system_group_uid
    system-uid: lary_system_uid
  group:
    same-day-create-max-count: 5
    allow-view-history-msg-status: true
  gift:
    table-num : 10
