DROP TABLE IF EXISTS `order`;
CREATE TABLE `order`  (
                          id bigint NOT NULL primary key comment 'format : 240920-xxxxxxxxxxx',
                          uid bigint COMMENT 'uid',
                          username varchar(40) COMMENT '用户名',
                          redpacket_id bigint COMMENT '红包id',
                          coupon_id bigint COMMENT '优惠券id',
                          goods_amount decimal(10, 2) COMMENT '商品价格',
                          goods_total_amount decimal(10,2) comment '商品总金额',
                          discount_store_amount decimal(10, 2) COMMENT '店铺优惠的金额',
                          discount_lary_amount decimal(10, 2) COMMENT '官方优惠的金额',
                          discount_redpacket_amount decimal(10, 2) COMMENT '红包优惠的金额',
                          freight_amount decimal(10, 2) COMMENT '运费',
                          pay_amount decimal(10,2) comment '实际支付金额',
                          consignee_detail varchar(255)COMMENT '详细地址',
                          consignee_phone varchar(20)COMMENT '收件人手机',
                          consignee_name varchar(255)COMMENT '收件人姓名',
                          shipper_detail varchar(255)COMMENT '详细地址',
                          shipper_phone varchar(20)COMMENT '收件人手机',
                          shipper_name varchar(255)COMMENT '收件人姓名',
                          goods_id bigint not null comment '货物id',
                          sku bigint not null comment 'sku',
                          goods_avatar varchar(255) COMMENT '商品图片',
                          goods_name varchar(255) COMMENT '商品名称',
                          goods_num int COMMENT '商品数量',
                          logistics_id int COMMENT '物流公司CODE',
                          logistics_name varchar(255) COMMENT '物流公司名称',
                          logistics__order_no  varchar(255) COMMENT '发货单号',
                          pay_order_no varchar(255) COMMENT '支付方式返回的交易号',
                          pay_status int COMMENT '付款状态',
                          deliver_status int COMMENT '货运状态',
                          pay_way int COMMENT '支付方式',
                          remark varchar(255) COMMENT '买家订单备注',
                          seller_remark varchar(255) COMMENT '商家订单备注',
                          store_id  int COMMENT '店铺ID',
                          store_name varchar(255)COMMENT '店铺名称',
                          store_avatar varchar(255) comment '店铺头像地址',
                          is_need_receipt bool COMMENT '是否需要发票',
                          deliver_code varchar(255)COMMENT '提货码',
                          is_can_return bool COMMENT '订单是否支持原路退回',
                          cancel_reason varchar(255) COMMENT '订单取消原因',
                          client_type int  COMMENT '客户端类型',
                          parent_id varchar(255)COMMENT '是否为其他订单下的订单，如果是则为依赖订单的sn，否则为空',
                          status int not null comment '订单状态',
                          create_at timestamp,
                          payment_at timestamp,
                          deliver_at timestamp,
                          complete_at timestamp,
                          update_at timestamp,
                          is_delete bool
);
drop table if exists `store_flow`;
create table `store_flow` (
                              id bigint primary key not null auto_increment  comment 'id',
                              store_id bigint not null comment '用户id',
                              idx_db int not null comment '库索引',
                              idx_table int not null comment '表索引',
                              order_id bigint NOT NULL  comment 'format : 240920-xxxxxxxxxxx',
                              goods_id bigint not null comment '货物id',
                              sku bigint not null comment 'sku',
                              goods_avatar varchar(255) COMMENT '商品图片',
                              goods_name varchar(255) COMMENT '商品名称',
                              goods_num int COMMENT '商品数量',
                              uid bigint not null comment '用户id',
                              pay_amount decimal(10,2) comment '实际支付金额',
                              status int not null comment '订单状态',
                              create_at timestamp
);
drop table if exists `user_flow`;
create table  `user_flow` (
                              id bigint not null primary key auto_increment  comment 'id',
                              uid bigint not null comment '用户id',
                              idx_db int not null comment '库索引',
                              idx_table int not null comment '表索引',
                              order_id bigint NOT NULL  comment 'format : 240920-xxxxxxxxxxx',
                              store_id  bigint COMMENT '店铺ID',
                              store_name varchar(255)COMMENT '店铺名称',
                              store_avatar varchar(255) comment '店铺头像地址',
                              goods_id bigint not null comment '货物id',
                              sku bigint not null comment 'sku',
                              goods_avatar varchar(255) COMMENT '商品图片',
                              goods_name varchar(255) COMMENT '商品名称',
                              goods_num int COMMENT '商品数量',
                              pay_amount decimal(10,2) comment '实际支付金额',
                              status int not null comment '订单状态',
                              create_at timestamp
);
DROP TABLE IF EXISTS `order_complaint`;
CREATE TABLE `order_complaint`  (
                                    id bigint primary key NOT NULL auto_increment COMMENT 'id',
                                    order_id bigint not null comment '订单id',
                                    uid bigint unsigned COMMENT 'uid',
                                    username varchar(255) COMMENT '用户名',
                                    appeal_content varchar(255)  COMMENT '申诉商家内容',
                                    appeal_images varchar(255) COMMENT '申诉商家上传的图片',
                                    appeal_at timestamp COMMENT '申诉商家时间',
                                    arbitration_result varchar(255) COMMENT '仲裁结果',
                                    complain_status int COMMENT '交易投诉状态',
                                    complain_topic varchar(255) COMMENT '投诉主题',
                                    consignee_address varchar(255) COMMENT '收货地址',
                                    consignee_mobile varchar(255) COMMENT '收货人手机',
                                    consignee_name varchar(255) COMMENT '收货人',
                                    content varchar(255) COMMENT '投诉内容',
                                    freight_amount decimal(10, 2) COMMENT '运费',
                                    goods_id varchar(255) COMMENT '商品ID',
                                    goods_image varchar(255) COMMENT '商品图片',
                                    goods_name varchar(255) COMMENT '商品名称',
                                    goods_amount decimal(10, 2) COMMENT '商品价格',
                                    goods_num int comment '商品数量',
                                    images text NULL COMMENT '投诉凭证图片',
                                    logistics_no varchar(255) COMMENT '物流单号',
                                    order_amount decimal(10, 2) COMMENT '订单金额',
                                    order_sn bigint COMMENT '订单编号',
                                    order_time datetime COMMENT '下单时间',
                                    store_id int COMMENT '店铺ID',
                                    store_name varchar(255) COMMENT '店铺名称',
                                    sku_id varchar(255) COMMENT 'sku',
                                    create_at timestamp,
                                    update_at timestamp,
                                    is_delete bool
) ;
DROP TABLE IF EXISTS `receipt`;
CREATE TABLE `receipt`  (
                            id bigint primary key NOT NULL auto_increment COMMENT 'ID',
                            order_id bigint not null comment '订单id',
                            uid bigint unsigned  COMMENT 'uid',
                            username varchar(255)  COMMENT '用户',
                            content varchar(255)  COMMENT '发票内容',
                            amount varchar(255)  COMMENT '发票金额',
                            status int COMMENT '发票状态',
                            title varchar(255)  COMMENT '发票抬头',
                            store_id varchar(255)  COMMENT '店铺ID',
                            store_name varchar(255)  COMMENT '店铺名称',
                            taxpayer_id varchar(255)  COMMENT '纳税人识别号',
                            create_at timestamp,
                            update_at timestamp,
                            is_delete bool
);
